### PR TITLE
Fix #142

### LINKED ISSUE #142: int() should decay to int(*)() in declarations
```c
int f(int g()) { return g(); }
int main() {
        return f(f);
}
<stdin>:3:19: error: invalid program: cannot implicitly convert 'int(*)(int() g)' to 'int()'
```

### PR DESCRIPTION
**Pull request by hdamron17**
Decay parameter of 'function returning type' to 'pointer to function returning type'

### CODE REVIEW

**Comment by hdamron17** [comment]
* Let me know if there is a better way to pattern match `ctype` as a `Type::Function`.
* I don't know the implications of creating a new Box (if any) since I am not a true Rustacean.
* I added a test C code, but should I add any unit test for something like this? The C code referenced in #142 segfaults because it calls `f()` with the wrong number of parameters so I used a more sensible test case.

**Comment by jyn514** [comment]
> Let me know if there is a better way to pattern match ctype as a Type::Function.

You can also use `is_function()` which I implemented on `Type`, but the way you have it now is fine.

> I don't know the implications of creating a new Box (if any) since I am not a true Rustacean.

This is fine (and actually required by the `Type` enum because it's a recursive type). All it does is move the struct to the heap, sort of like `new` in C++.

> I added a test C code, but should I add any unit test for something like this? The C code referenced in #142 segfaults because it calls f() with the wrong number of parameters so I used a more sensible test case.

The unit tests are currently [pretty ugly](https://github.com/jyn514/rcc/blob/master/src/parse/decl.rs#L2135) so I think a runner test is fine. The segfault in 142 is because it calls `f()` infinitely many times and runs out of stack space.

File: src/parse/decl.rs [hunk 1]
```diff
@@ -947,6 +947,14 @@ impl<I: Iterator<Item = Lexeme>> Parser<I> {
                 if let Type::Array(to, _) = ctype {
                     ctype = Type::Pointer(to);
                 }
+
+                // Fix #142 (C11 Standard 6.7.6.3 paragraph 8)
```
Comment (jyn514) [inline src/parse/decl.rs:951]: Normally I put a link to the issue in the test case, not in the code, unless it's something really hacky. The link to the standard is good, though.

Comment (hdamron17) [reply src/parse/decl.rs:951]: Sounds good. I'll change to use `is_function()` while I'm making this change anyway.
