### PR TITLE
Static keyword in for array sizes in function parameters

### LINKED ISSUE #62: static in array parameters
Thanks to Tachyon.

```c
$ cargo run
void f(int v[static 5]);
<stdin>:1:21: error: expected ')', got '5'
```

Should parse as an array known to have at least length 5.

### PR DESCRIPTION
**Pull request by pythondude325**
Allows the use of the `static` keyword for array sizes in function parameters.

Fixes #62

### CODE REVIEW

File: src/parse/decl.rs [hunk 1]
```diff
@@ -918,11 +918,12 @@ impl<I: Iterator<Item = Lexeme>> Parser<I> {
     fn postfix_type(
         &mut self,
         mut prefix: Option<Declarator>,
+        allow_abstract: bool,
     ) -> Result<Option<Declarator>, SyntaxError> {
         // postfix
         while let Some(data) = self.peek_token() {
             prefix = match data {
-                // array
```
Comment (jyn514) [inline src/parse/decl.rs]: lol this comment looks so sad. Thanks for changing it haha

File: src/parse/decl.rs [hunk 2]
```diff
@@ -931,6 +932,20 @@ impl<I: Iterator<Item = Lexeme>> Parser<I> {
                             next: prefix.map(Box::new),
                         })
                     } else {
+                        if let Some(keyword) = self.match_next(&Token::Keyword(Keyword::Static)) {
+                            if allow_abstract {
+                                // TODO: Add information for the compiler to know
+                                // to warn if `NULL` is passed into the function
+                            } else {
+                                return Err(SyntaxError(Locatable {
```
Comment (jyn514) [inline src/parse/decl.rs]: This is a semantic error, not a syntactic one. The difference is that semantic errors are recoverable while syntax errors are not. Use `self.semantic_err` instead of returning an error from the function.

File: src/parse/decl.rs [hunk 3]
```diff
@@ -1799,6 +1814,25 @@ mod tests {
...
+                    qualifiers: Default::default(),
+                    storage_class: Default::default(),
+                    init: true,
+                }],
+                varargs: false
+            })
+        ));
+
+        assert!(parse("int b[static 10];").unwrap().is_err());
+    }
```
Comment (jyn514) [inline src/parse/decl.rs]: Looks great, thank you so much for adding this!
