### PR TITLE
Correctly calculate struct size from alignment

### LINKED ISSUE #278: [ICE] Incorrect memcpy for struct when alignment < size
**Expected behavior**
RCC should memcpy the whole struct up to the nearest multiple of the alignment.

**Actual Behavior**
RCC only copies the size of the struct, without the padding bits.

**Code**

```c
int main() {
	struct S { int *y, z; } s, ss;
	s = ss;
}
The application panicked (crashed).
Message:  `size` is smaller than `dest` and `src`'s alignment value.
Location: /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-frontend-0.58.0/src/frontend.rs:820
```

<details><summary>Backtrace</summary>

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                          (4 post panic frames hidden)                          
 4: cranelift_frontend::frontend::FunctionBuilder::emit_small_memmove::ha82eaace5e0d7fa5
    at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-frontend-0.58.0/src/frontend.rs:820
 5: rcc::ir::expr::<impl rcc::ir::Compiler>::assignment::hba6a3763c064d501
    at src/ir/expr.rs:511
 6: rcc::ir::expr::<impl rcc::ir::Compiler>::compile_expr::hf2862280ec6077e1
    at src/ir/expr.rs:102
 7: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt::h7e24c153b5470ada
    at src/ir/stmt.rs:37
 8: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_all::hf59a3cda5830301d
    at src/ir/stmt.rs:15
 9: rcc::ir::Compiler::compile_func::hff5573813724a524
    at src/ir/mod.rs:321
10: rcc::ir::compile::h9967cd2f3830dff1
    at src/ir/mod.rs:75
11: rcc::compile::h56c7e62b242f942d
    at src/lib.rs:179
12: rcc::real_main::h6aa73fa5e305122a
    at src/main.rs:109
13: rcc::main::hd71a6cc32e4b0a3f
    at src/main.rs:172
```

</details>

Thanks to @Byter09 for the fuzzing.

### PR DESCRIPTION
**Pull request by repnop**
Fixes #278.

This change takes struct alignment when calculating the size, specifically that it should round up to the nearest multiple of alignment. It also changes the `complex_type_for_size` to use all `char`s instead of filling in with larger types which have a higher alignment requirement.

### CODE REVIEW

File: src/arch/mod.rs [hunk 1]
```diff
@@ -72,9 +72,16 @@ impl StructType {
...
-        })
+        symbols
+            .iter()
+            .try_fold(0, |offset, symbol| {
+                Ok(StructType::next_offset(offset, &symbol.ctype)?)
+            })
+            .and_then(|size_t| {
+                let align_minus_one = self.align()? - 1;
+
+                Ok((size_t + align_minus_one) & !align_minus_one)
```
Comment (jyn514) [inline src/arch/mod.rs]:
```suggestion
                // round up to the nearest multiple of `align`
                Ok((size_t + align_minus_one) & !align_minus_one)
```

File: src/arch/mod.rs [hunk 2]
```diff
@@ -259,27 +266,7 @@ mod tests {
         }
     }
     fn complex_type_for_size(size: u16) -> Type {
```
Comment (jyn514) [inline src/arch/mod.rs]: Can you inline this function now that it's just a one-liner?

File: tests/runner-tests/expr/assign/struct_align.c [hunk 3]
```diff
@@ -0,0 +1,5 @@
+// succeeds
+int main() {
+	struct S { int *y, z; } s, ss;
+	s = ss;
```
Comment (jyn514) [inline tests/runner-tests/expr/assign/struct_align.c]: Can you also check that it correctly copies?
```suggestion
// code: 1
int main() {
	struct S { int *y, z; } s, ss;
	ss.z = 1;
	s = ss;
	return s.z;
```

File: src/arch/mod.rs [hunk 4]
```diff
@@ -349,7 +335,7 @@ mod tests {
     #[test]
     fn char_struct() {
         let char_struct = type_for_size(5);
-        assert_eq!(char_struct.alignof().unwrap(), 4);
+        assert_eq!(char_struct.alignof().unwrap(), 1);
         assert_offset(vec![Type::Int(true), Type::Char(true)], 1, 4);
         assert_eq!(char_struct.sizeof().unwrap(), 5);
     }
```
Comment (jyn514) [inline src/arch/mod.rs]: Could you add one last test that makes sure this has the correct alignment? Something like

```
#[test]
fn align() 
   let ty = struct_for_types(vec![Int(True), Int]);
   assert_eq!(ty.alignof(), Ok(8));
}
```

Comment (repnop) [reply src/arch/mod.rs]: that should be an alignment of 4, correct?

Comment (jyn514) [reply src/arch/mod.rs]: Whoops, I meant for the first type to be a pointer, not an int.
